"""Run a node-sensitivity analysis for a trained GraphDeepTDA model."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import torch

from mlcolvar.graph.cvs.supervised.deeptda import GraphDeepTDA
from mlcolvar.graph.examples.toy_dataset import ToyDatasetConfig, build_toy_dataset
from mlcolvar.graph.explain.sensitivity import graph_node_sensitivity


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "checkpoint",
        type=Path,
        help="Checkpoint generated by examples/train_deeptda.py",
    )
    parser.add_argument(
        "--n-configs",
        type=int,
        default=8,
        help="Number of configurations to analyse.",
    )
    parser.add_argument(
        "--component",
        type=int,
        default=0,
        help="Index of the CV component for which sensitivities are computed.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        help="Device used to evaluate the gradients (e.g. 'cpu' or 'cuda').",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    checkpoint_path: Path = args.checkpoint

    if not checkpoint_path.exists():
        raise FileNotFoundError(
            f"Checkpoint {checkpoint_path} not found. Run train_deeptda.py first."
        )

    dataset = build_toy_dataset(ToyDatasetConfig(n_samples=max(args.n_configs, 16)))
    subset = dataset[: args.n_configs]

    model = GraphDeepTDA.load_from_checkpoint(str(checkpoint_path), map_location=args.device)
    model.eval()

    torch.set_grad_enabled(True)
    results = graph_node_sensitivity(
        model=model,
        dataset=subset,
        component=args.component,
        device=args.device,
        batch_size=args.n_configs,
        show_progress=False,
    )

    node_indices = np.arange(subset[0].num_nodes)
    sensitivities = results["sensitivities_components"][0]
    for atom_index, sensitivity in zip(node_indices, sensitivities):
        print(f"Atom {atom_index}: sensitivity = {sensitivity:.4f}")


if __name__ == "__main__":
    main()
